[project]
name = "blck"
version = "0.1.0"
description = "An ephemeral pastebin/URL-shortener"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Jinja2==3.1.5",
    "sanic==24.6.0",
    "python-magic==0.4.27",
    "aiologger==0.7.0"
]
